import Pizza1 from './img/categories/pizza/pizza-hawaiian.jpeg'
import Pizza2 from './img/categories/pizza/pizza-pepperoni.jpeg'
import Pizza3 from './img/categories/pizza/pizza-bbq.jpeg'
import Pizza4 from './img/categories/pizza/pizza-texas.jpeg'
import Pizza5 from './img/categories/pizza/pizza-four-seasons.jpeg'
import Pizza6 from './img/categories/pizza/pizza-mushroom.jpeg'
import Pizza7 from './img/categories/pizza/pizza-margherita.jpeg'
import Sushi1 from './img/categories/sushi/sushi-california.jpeg'
import Sushi2 from './img/categories/sushi/sushi-philadelphia.jpeg'
import Sushi3 from './img/categories/sushi/sushi-maki-with-salmon.jpeg'
import Sushi4 from './img/categories/sushi/sushi-hot-crab.jpeg'
import Sushi5 from './img/categories/sushi/sushi-tuna-and-shrimp.jpeg'
import Wok1 from './img/categories/wok/wok-teriyaki-chicken-with-udon.jpeg'
import Wok2 from './img/categories/wok/wok-rice-with-beef-and-egg.jpeg'
import Wok3 from './img/categories/wok/wok-seafood-with-udon-noodles.jpeg'
import Wok4 from './img/categories/wok/wok-pork-with-udon-noodles.jpeg'
import Salad1 from './img/categories/salads/salad-caesar.jpeg'
import Salad2 from './img/categories/salads/salad-greek.jpeg'
import Salad3 from './img/categories/salads/salad-shrimps-and-mango.jpeg'
import Salad4 from './img/categories/salads/salad-warm-with-chicken-strips.jpeg'
import Soup1 from './img/categories/soups/soups-borsch.jpeg'
import Soup2 from './img/categories/soups/soups-kimchi.jpeg'
import Soup3 from './img/categories/soups/soups-tom-yum.jpeg'
import Soup4 from './img/categories/soups/soups-finnish-with-salmon.jpeg'
import Soup5 from './img/categories/soups/soups-solyanka.jpeg'
import Dessert1 from './img/categories/dessert/dessert-caramel-cheesecake.jpeg'
import Dessert2 from './img/categories/dessert/dessert-cake-napoleon.jpeg'
import Dessert3 from './img/categories/dessert/dessert-chocolate-muffin.jpeg'
import Dessert4 from './img/categories/dessert/dessert-mochi-cake-mango-passionfruit.jpeg'

export const Categories = {
    PIZZA: "pizza", 
    SUSHI: "sushi", 
    WOK: "wok", 
    SALADS: "salads", 
    SOUPS: "soups", 
    DESSERT: "dessert"
}

export const items = [
    {
        id: 1,
        img: Pizza1,
        category: "pizza",
        trending: false,
        title: "Hawaiian",
        trending: true,
        description: "tender ham, chicken and juicy pineapple",
        descriptionFull: "Pizza for connoisseurs of non-standard flavor combinations: tender ham, chicken and juicy pineapple.",
        price: 479,
        currency: "₽",
        basketCount: 0,
        weight: 580,
        proteins: 9,
        fats: 8,
        carbs: 19,
        energyValue: 183,
        ingredients: "Marinated chicken fillet, ham, canned pineapple, mozzarella cheese, tomato sauce, yeast dough, premium flour from durum wheat"
    },
    {
        id: 2,
        img: Pizza2,
        category: "pizza",
        trending: false,
        title: "Pepperoni",
        description: "spicy pizza with spicy Italian pepperoni and jalapeno peppers",
        descriptionFull: "Simple, like all ingenious, spicy pizza with spicy Italian pepperoni sausage and jalapeno peppers.",
        price: 479,
        currency: "₽",
        basketCount: 0,
        weight: 530,
        proteins: 13,
        fats: 12,
        carbs: 17,
        energyValue: 232,
        ingredients: "Pepperoni sausage, mozzarella cheese, pickled jalapeno peppers, tomato sauce, yeast dough, durum wheat flour"
    },
    {
        id: 3,
        img: Pizza3,
        category: "pizza",
        trending: false,
        title: "BBQ",
        description: "fragrant bacon, chicken, ham and sweet bell pepper, flavored with bbq sauce",
        descriptionFull: "Fragrant bacon, chicken, ham and sweet bell pepper. The unique taste of pizza gives a traditional American barbecue sauce.",
        price: 619,
        currency: "₽",
        basketCount: 0,
        weight: 670,
        proteins: 12,
        fats: 10,
        carbs: 18,
        energyValue: 198,
        ingredients: "Marinated chicken fillet, ham, bacon, mozzarella cheese, red bell pepper, red onion, tomato barbecue sauce, tomato sauce, yeast dough, durum wheat flour"
    },
    {
        id: 4,
        img: Pizza4,
        category: "pizza",
        trending: false,
        title: "Texas",
        description: "ham, fragrant bacon, chicken and spicy pepperoni with tender mozzarella and emmental",
        descriptionFull: "Ham, fragrant bacon, chicken and spicy pepperoni with tender mozzarella and emmental.",
        price: 619,
        currency: "₽",
        basketCount: 0,
        weight: 655,
        proteins: 11,
        fats: 10,
        carbs: 13,
        energyValue: 191,
        ingredients: "Ham, marinated chicken fillet, pepperoni sausage, bacon, mozzarella cheese, emmental cheese, tomato sauce, yeast dough, durum wheat flour"
    },
    {
        id: 5,
        img: Pizza5,
        category: "pizza",
        trending: false,
        title: "Four seasons",
        description: "pepperoni, ham, mushrooms and bright vegetable mix",
        descriptionFull: "Two hearty meat and two vegetarian pizzas in one - pepperoni, ham, mushrooms and a bright vegetable mix.",
        price: 569,
        currency: "₽",
        basketCount: 0,
        weight: 585,
        proteins: 10,
        fats: 9,
        carbs: 17,
        energyValue: 192,
        ingredients: "Pepperoni sausage, ham, mushrooms, tomatoes, zucchini, red onion, black olives, feta cheese, mozzarella cheese, tomato sauce, oregano, yeast dough, durum wheat flour"
    },
    {
        id: 6,
        img: Pizza6,
        category: "pizza",
        trending: false,
        title: "Mushroom",
        description: "champignons with mozzarella and cheddar, pickled cucumbers, smoked potatoes and red onions with tartar sauce",
        descriptionFull: "One has only to bite through it, and under the cheese duet of mozzarella and cheddar there will be tender champignons, pickled cucumbers, smoked potatoes and red onions with tartar sauce on a traditional dough.",
        price: 459,
        currency: "₽",
        basketCount: 0,
        weight: 680,
        proteins: 9,
        fats: 10,
        carbs: 18,
        energyValue: 195,
        ingredients: "Champignons, smoked potatoes, mozzarella cheese, cheddar cheese, tartar sauce, pickled cucumbers, red onion, yeast dough, flour"
    },
    {
        id: 7,
        img: Pizza7,
        category: "pizza",
        trending: false,
        title: "Margherita",
        description: "lightly baked tomato cubes, soft gooey mozzarella and a dash of oregano for flavor",
        descriptionFull: "Lightly baked tomato cubes, soft gooey mozzarella and a touch of oregano for flavor - a classic Margherita.",
        price: 459,
        currency: "₽",
        basketCount: 0,
        weight: 565,
        proteins: 9,
        fats: 8,
        carbs: 18,
        energyValue: 182,
        ingredients: "Tomatoes, mozzarella cheese, tomato sauce, oregano, yeast dough, durum wheat flour"
    },
    {
        id: 8,
        img: Sushi1,
        category: "sushi",
        trending: true,
        title: "California",
        description: "snow crab, avocado and cucumber in nori, covered with rice and masago caviar",
        descriptionFull: "A popular roll according to a traditional recipe: snow crab, avocado and cucumber in nori, covered with rice and masago caviar.",
        price: 359,
        currency: "₽",
        basketCount: 0,
        weight: 235,
        proteins: 6,
        fats: 5,
        carbs: 39,
        energyValue: 230,
        ingredients: "Snow crab, rice, nori seaweed, avocado, fresh cucumber, orange masago caviar"
    },
    {
        id: 9,
        img: Sushi2,
        category: "sushi",
        trending: true,
        title: "Philadelphia",
        description: "with faroese salmon, curd cheese and fresh cucumber",
        descriptionFull: "Big Philadelphia with Faroese salmon, cream cheese and fresh cucumber.",
        price: 449,
        currency: "₽",
        basketCount: 0,
        weight: 280,
        proteins: 9,
        fats: 10,
        carbs: 32,
        energyValue: 248,
        ingredients: "Salmon, rice, curd cheese, cucumber, nori seaweed"
    },
    {
        id: 10,
        img: Sushi3,
        category: "sushi",
        trending: false,
        title: "Maki with salmon",
        description: "tender faroese salmon, rice and nori - a simple and popular roll for fans of the classics",
        descriptionFull: "Tender Faroese salmon, rice and nori is a simple and popular roll for connoisseurs of the classics.",
        price: 259,
        currency: "₽",
        basketCount: 0,
        weight: 110,
        proteins: 10,
        fats: 5,
        carbs: 47,
        energyValue: 272,
        ingredients: "Rice, salmon, nori seaweed"
    },
    {
        id: 11,
        img: Sushi4,
        category: "sushi",
        trending: false,
        title: "Hot crab",
        description: "tender snow crab meat, scrambled eggs, curd cheese and fresh cucumber in nori with masago caviar topped with mozzarella cheese",
        descriptionFull: "Tender snow crab meat, scrambled eggs, curd cheese and fresh cucumber in nori with masago caviar topped with mozzarella cheese.",
        price: 409,
        currency: "₽",
        basketCount: 0,
        weight: 315,
        proteins: 10,
        fats: 11,
        carbs: 29,
        energyValue: 250,
        ingredients: "Rice, mozzarella cheese, snow crab, curd cheese, scrambled eggs, orange masago caviar, cucumber, nori seaweed"
    },
    {
        id: 12,
        img: Sushi5,
        category: "sushi",
        trending: false,
        title: "Tuna and shrimp",
        description: "tuna, tender shrimp, soft curd cheese and fresh cucumber in fragrant sesame",
        descriptionFull: "Spicy classic roll with tuna, tender shrimp, soft curd cheese and fresh cucumber in fragrant sesame seeds.",
        price: 419,
        currency: "₽",
        basketCount: 0,
        weight: 225,
        proteins: 9,
        fats: 8,
        carbs: 38,
        energyValue: 267,
        ingredients: "Tuna, tiger prawns, rice, curd cheese, cucumber, green onion, spicy sauce, sesame, nori seaweed"
    },
    {
        id: 13,
        img: Wok1,
        category: "wok",
        trending: true,
        title: "Teriyaki chicken with udon",
        description: "chicken fillet fried in teriyaki sauce, wheat noodles, vegetables and sesame seeds",
        descriptionFull: "Chicken fillet fried in teriyaki sauce, wheat noodles, vegetables and fragrant sesame seeds - nothing more, just a hearty Wok.",
        price: 319,
        currency: "₽",
        basketCount: 0,
        weight: 320,
        proteins: 11,
        fats: 13,
        carbs: 23,
        energyValue: 250,
        ingredients: "Udon noodles, chicken, red bell pepper, onion, carrot, teriyaki sauce, green onion, white sesame"
    },
    {
        id: 14,
        img: Wok2,
        category: "wok",
        trending: false,
        title: "Rice with beef and egg",
        description: "thinly sliced beef, egg, wok-fried fresh vegetables and rice",
        descriptionFull: "Classic Chinese flavor combination: thinly sliced beef, egg, fresh vegetables and wok-fried rice.",
        price: 419,
        currency: "₽",
        basketCount: 0,
        weight: 360,
        proteins: 15,
        fats: 12,
        carbs: 21,
        energyValue: 251,
        ingredients: "Rice, beef, chicken egg, red bell pepper, carrot, onion, teriyaki sauce, green onion, white sesame"
    },
    {
        id: 15,
        img: Wok3,
        category: "wok",
        trending: false,
        title: "Seafood with udon",
        description: "prawns and mussels, salmon, vegetables and wheat noodles in teriyaki sauce, seasoned with white sesame seeds",
        descriptionFull: "Seafood with an Asian flavor: large prawns and mussels, salmon, vegetables and wheat noodles in teriyaki sauce, seasoned with white sesame seeds.",
        price: 469,
        currency: "₽",
        basketCount: 0,
        weight: 355,
        proteins: 5,
        fats: 4,
        carbs: 10,
        energyValue: 95,
        ingredients: "Udon noodles, teriyaki sauce, tiger prawns, giant mussels, salmon, red bell pepper, carrot, onion, vegetable oil, white sesame, green onion"
    },
    {
        id: 16,
        img: Wok4,
        category: "wok",
        trending: false,
        title: "Pork with udon",
        description: "pork with spices, sweet bell pepper, carrots and onions fried in a wok with teriyaki sauce",
        descriptionFull: "Pork with spices, Chinese wheat noodles, sweet bell peppers, carrots and onions fried in a wok with teriyaki sauce.",
        price: 319,
        currency: "₽",
        basketCount: 0,
        weight: 320,
        proteins: 13,
        fats: 14,
        carbs: 24,
        energyValue: 272,
        ingredients: "Udon noodles, pork, red bell pepper, onion, carrot, teriyaki sauce, green onion, white sesame"
    },
    {
        id: 17,
        img: Salad1,
        category: "salads",
        trending: true,
        title: "Caesar with chicken",
        description: "fried chicken fillet, fragrant parmesan, cherry tomatoes, croutons, lettuce and sauce",
        descriptionFull: "Salad with fried chicken fillet, fragrant parmesan, cherry tomatoes, croutons, lettuce and special sauce according to a traditional American recipe.",
        price: 319,
        currency: "₽",
        basketCount: 0,
        weight: 170,
        proteins: 10,
        fats: 27,
        carbs: 29,
        energyValue: 401,
        ingredients: "Chicken, parmesan cheese, cherry tomatoes, iceberg lettuce, croutons, caesar sauce"
    },
    {
        id: 18,
        img: Salad2,
        category: "salads",
        trending: false,
        title: "Greek salad",
        description: "vegetables, fresh feta cheese and black olives with olive oil dressing",
        descriptionFull: "Juicy crispy salad according to a traditional recipe: vegetables, fresh feta cheese and black olives with olive oil dressing.",
        price: 199,
        currency: "₽",
        basketCount: 0,
        weight: 180,
        proteins: 4,
        fats: 9,
        carbs: 3,
        energyValue: 113,
        ingredients: "Chicken, parmesan cheese, cherry tomatoes, iceberg lettuce, croutons, caesar sauce"
    },
    {
        id: 19,
        img: Salad3,
        category: "salads",
        trending: false,
        title: "Shrimps and mango",
        description: "a combination of ripe mango, juicy tiger prawns and avocado with crispy romaine lettuce and cherry tomatoes",
        descriptionFull: "A bright and unexpected combination of ripe mango, juicy tiger prawns and avocado with the addition of crispy romaine lettuce and cherry tomatoes. Seasoned with mango-creamy and sweet oyster sauces.",
        price: 389,
        currency: "₽",
        basketCount: 0,
        weight: 195,
        proteins: 9,
        fats: 6,
        carbs: 14,
        energyValue: 146,
        ingredients: "Tiger prawns, mango, avocado, romaine lettuce, cherry tomatoes, sweet oyster sauce (sweet chili sauce, oyster sauce, lime juice), mango sauce (mango, cream 33%, lime juice, turmeric), lime"
    },
    {
        id: 20,
        img: Salad4,
        category: "salads",
        trending: false,
        title: "Warm with chicken strips",
        description: "chicken strips and bacon in a warm salad with a mix of romaine and iceberg, juicy tomatoes, crispy cucumbers and caramelized onions",
        descriptionFull: "American-style freshness: chicken strips and bacon in a warm salad with a mix of romaine and iceberg, juicy tomatoes, crispy cucumbers and caramelized onions.",
        price: 249,
        currency: "₽",
        basketCount: 0,
        weight: 180,
        proteins: 9,
        fats: 12,
        carbs: 5,
        energyValue: 164,
        ingredients: "Breaded chicken breast fillet, bacon, iceberg lettuce, romaine lettuce, fresh tomatoes, fresh cucumber, maxi sauce, caramelized onion"
    },
    {
        id: 21,
        img: Soup1,
        category: "soups",
        trending: true,
        title: "Borsch",
        description: "tender beef, rich broth with fresh vegetables (beets, cabbage, onions and carrots)",
        descriptionFull: "Fragrant borsch with tender beef, rich beef broth and fresh vegetables (beets, cabbage, onions and carrots). Cooked with the addition of tomato paste and garlic. Delivered with sour cream.",
        price: 249,
        currency: "₽",
        basketCount: 0,
        weight: 280,
        proteins: 3,
        fats: 6,
        carbs: 11,
        energyValue: 108,
        ingredients: "Beets, cabbage, beef, onions, carrots, beef broth, water, tomato paste, vegetable oil, salt, vinegar 9%, garlic, sugar, bay leaf, sour cream"
    },
    {
        id: 22,
        img: Soup2,
        category: "soups",
        trending: false,
        title: "Kimchi",
        description: "spicy, light and, by the way, very tasty",
        descriptionFull: "A cult Korean dish: spicy, light and, by the way, very tasty soup.",
        price: 199,
        currency: "₽",
        basketCount: 0,
        weight: 330,
        proteins: 2,
        fats: 2,
        carbs: 1,
        energyValue: 30,
        ingredients: "Kimchi cabbage, broth, chicken egg, Wakame seaweed, Tofu cheese, green onion, sesame"
    },
    {
        id: 23,
        img: Soup3,
        category: "soups",
        trending: false,
        title: "Tom Yum",
        description: "with mussels, tiger prawns, sweet cherry tomatoes and shiitake mushrooms",
        descriptionFull: "Spicy Thai soup in chicken broth with mussels, tiger prawns, sweet cherry tomatoes and shiitake mushrooms.",
        price: 399,
        currency: "₽",
        basketCount: 0,
        weight: 380,
        proteins: 12,
        fats: 5,
        carbs: 8,
        energyValue: 130,
        ingredients: "Tom Yum broth, coconut milk, tom yum paste, cream, ginger, lemongrass, lime juice, fish sauce, rice, shrimps, mussels, shiitake mushrooms, leek, cherry tomatoes, Sriracha sauce, fresh cilantro"
    },
    {
        id: 24,
        img: Soup4,
        category: "soups",
        trending: false,
        title: "Finnish with salmon",
        description: "tender salmon, potatoes, tomato cubes, leeks and fragrant dill",
        descriptionFull: "Hearty creamy soup according to a traditional Finnish recipe: tender salmon, potatoes, tomato cubes, leeks and fragrant dill.",
        price: 369,
        currency: "₽",
        basketCount: 0,
        weight: 300,
        proteins: 3,
        fats: 7,
        carbs: 3,
        energyValue: 85,
        ingredients: "Salmon, potatoes, tomatoes, leek, dill, cream, Hondashi broth, ground black pepper, salt"
    },
    {
        id: 25,
        img: Soup5,
        category: "soups",
        trending: false,
        title: "Solyanka",
        description: "thick meat with chicken and hunting sausages, olives, lemon and fresh sour cream add brightness to the taste",
        descriptionFull: "Thick meat hodgepodge with chicken and hunting sausages. Olives and lemon add brightness to the taste, and a portion of fresh sour cream completes the composition.",
        price: 259,
        currency: "₽",
        basketCount: 0,
        weight: 290,
        proteins: 3,
        fats: 4,
        carbs: 10,
        energyValue: 84,
        ingredients: "Chicken fillet, hunting sausages, chicken broth, black olives, pickles, onions, tomato paste, sour cream, garlic, lemon, sugar, salt, ground black pepper"
    },
    {
        id: 26,
        img: Dessert1,
        category: "dessert",
        trending: true,
        title: "Caramel cheesecake",
        description: "made from cottage cheese, cocoa, peanuts and a very sweet glaze",
        descriptionFull: "Sweet tooth will definitely like: caramel cheesecake made of cottage cheese, cocoa, peanuts and very sweet glaze.",
        price: 279,
        currency: "₽",
        basketCount: 0,
        weight: 100,
        proteins: 8,
        fats: 25,
        carbs: 36,
        energyValue: 400,
        ingredients: "Cottage cheese, cocoa, peanuts, confectionery glaze, salt, sugar, water, milk, butter, flour"
    },
    {
        id: 27,
        img: Dessert2,
        category: "dessert",
        trending: false,
        title: "Cake Napoleon",
        description: "puff pastry and soft buttercream",
        descriptionFull: "Puff pastry and soft buttercream - a familiar taste in a new form. Take it with you and enjoy wherever you want.",
        price: 299,
        currency: "₽",
        basketCount: 0,
        weight: 130,
        proteins: 3,
        fats: 19,
        carbs: 24,
        energyValue: 278,
        ingredients: "Yeast-free puff pastry, custard, cream, powdered sugar"
    },
    {
        id: 28,
        img: Dessert3,
        category: "dessert",
        trending: false,
        title: "Chocolate muffin",
        description: "biscuit dough with delicate chocolate filling",
        descriptionFull: "Classic biscuit dough muffin with delicate chocolate filling.",
        price: 149,
        currency: "₽",
        basketCount: 0,
        weight: 120,
        proteins: 10,
        fats: 29,
        carbs: 48,
        energyValue: 351,
        ingredients: "Flour, chicken eggs, sugar, vegetable oil, chocolate muffin mix, chocolate filling, xanth gum"
    },
    {
        id: 29,
        img: Dessert4,
        category: "dessert",
        trending: false,
        title: "Mochi cake Mango-Passionfruit",
        description: "with a delicate slightly stretchy texture and moderately sweet and sour taste",
        descriptionFull: "Japanese mochi dessert with mango-passion fruit flavor. For cooking, flour is used from the ancient variety of mochigome rice. The dessert is obtained with a delicate, slightly stretchy texture and moderately sweet and sour taste.",
        price: 199,
        currency: "₽",
        basketCount: 0,
        weight: 40,
        proteins: 3,
        fats: 10,
        carbs: 40,
        energyValue: 269,
        ingredients: "Curd cheese, molasses, confectionery glaze, rice flour, mango puree, sunflower oil, tapioca starch, passion fruit puree, sugar"
    },
] 